spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgres://localhost:5432/library
    username: postgres
    password: postgres_password
    driver-class-name: org.postgresql.Driver
